# Generated by Django 4.0.5 on 2022-06-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Givegift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_participant', models.CharField(max_length=20, verbose_name='Vaše jméno')),
                ('last_name_participant', models.CharField(max_length=50, verbose_name='Vaše příjmení')),
                ('email_participant', models.EmailField(max_length=50, verbose_name='Váš email')),
                ('messenger_participant', models.CharField(max_length=150, verbose_name='Jakákoli sociální síť')),
            ],
            options={
                'verbose_name': 'Všechny formulaře',
                'verbose_name_plural': 'Všechny e-mailové adresy pro dárek',
            },
        ),
    ]
