# Generated by Django 4.0.5 on 2022-06-14 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='givegift',
            options={'verbose_name': 'Všechny formulaře', 'verbose_name_plural': 'Všechny e-mailové adresy pro dárek'},
        ),
    ]
