# Generated by Django 4.0.5 on 2022-06-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allnews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Název')),
                ('anons', models.CharField(max_length=250, verbose_name='Upoutávka')),
                ('full_text', models.TextField(verbose_name='Článek')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Datum změny')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Všechny novinky',
                'verbose_name_plural': 'Novinky',
            },
        ),
    ]
