# Generated by Django 4.0.5 on 2022-07-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_allnews_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allnews',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Všechny novinky', 'verbose_name_plural': 'Novinky'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Všechny kategorie', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterField(
            model_name='allnews',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Vydání'),
        ),
        migrations.AlterField(
            model_name='allnews',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Fotografie'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Kategorie'),
        ),
    ]
