# Generated by Django 4.0.5 on 2022-07-01 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_allnews_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allnews',
            name='anons',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(35)], verbose_name='Upoutávka'),
        ),
        migrations.AlterField(
            model_name='allnews',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(35)], verbose_name='Název'),
        ),
    ]
