# Generated by Django 4.0.5 on 2022-06-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_premierleague'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laliga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Název')),
                ('anons', models.CharField(max_length=250, verbose_name='Upoutávka')),
                ('full_text', models.TextField(verbose_name='Článek')),
                ('date', models.DateTimeField(verbose_name='Datum publikace')),
            ],
            options={
                'verbose_name': 'Všechny novinky PL',
                'verbose_name_plural': 'La Liga',
            },
        ),
    ]
