# Generated by Django 4.0.5 on 2022-06-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_seriaa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newtransfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_transfer', models.CharField(max_length=100, verbose_name='Jmeno')),
                ('last_name_transfer', models.CharField(max_length=100, verbose_name='Příjmení')),
                ('last_club', models.CharField(max_length=100, verbose_name='Poslední tým')),
                ('current_club', models.CharField(max_length=100, verbose_name='Současný tým')),
                ('price_transfer', models.IntegerField(verbose_name='Cena v dolarech')),
                ('contract_type', models.CharField(choices=[('one', 'Nákup'), ('two', 'Nájem'), ('three', 'Volný agent')], max_length=250, verbose_name='Smluvní typ')),
                ('contract_time', models.IntegerField(verbose_name='Smluvní doba v letech')),
            ],
            options={
                'verbose_name': 'Všechny transfers',
                'verbose_name_plural': 'Transfers',
            },
        ),
    ]
